CATALOG_SEED_VERSION = "2026-07-09-sprint-2-1"

SEED_PRODUCTS = [   {   'brand': 'AetherStreet',
        'category': 'T-Shirts',
        'collection_name': 'Sartorial Slouch',
        'color': 'Black',
        'description': 'Boxy-fit, heavy 240gsm cotton t-shirt with a vintage '
                       'wash. Prefect streetwear staple.',
        'gender': 'Unisex',
        'id': 1,
        'image_path': 'images/products/classic_heavyweight_tee.jpg',
        'name': 'Classic Heavyweight Cotton Tee',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 35.0,
        'season': 'Summer',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 120,
        'style_tags': 'Streetwear,Casual'},
    {   'brand': 'Loom & Craft',
        'category': 'T-Shirts',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'White',
        'description': 'Ultra-soft luxury Pima cotton t-shirt with a slim '
                       'silhouette and clean stitched hems.',
        'gender': 'Men',
        'id': 2,
        'image_path': 'images/products/pima_minimalist_tee.jpg',
        'name': 'Pima Cotton Minimalist Tee',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 45.0,
        'season': 'All-Season',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 80,
        'style_tags': 'Minimalist,Casual'},
    {   'brand': 'K-Wave Studio',
        'category': 'T-Shirts',
        'collection_name': 'Sartorial Slouch',
        'color': 'Beige',
        'description': 'Wide, boxy fit tee with relaxed drop shoulders and an '
                       'embroidered chest logo. Inspired by Seoul streetwear.',
        'gender': 'Unisex',
        'id': 3,
        'image_path': 'images/products/oversized_drop_tee.jpg',
        'name': 'Oversized Drop-Shoulder Tee',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 38.0,
        'season': 'Summer',
        'size_options': 'M,L,XL',
        'stock_quantity': 150,
        'style_tags': 'Korean Fashion,Streetwear'},
    {   'brand': 'Belgravia Tailors',
        'category': 'T-Shirts',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Navy',
        'description': 'Breathable pique knit polo with mother-of-pearl '
                       'buttons and subtle crown embroidery. Timeless class.',
        'gender': 'Men',
        'id': 4,
        'image_path': 'images/products/pique_polo.jpg',
        'name': 'Pique Cotton Polo Shirt',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 75.0,
        'season': 'Summer',
        'size_options': 'S,M,L,XL,XXL',
        'stock_quantity': 50,
        'style_tags': 'Old Money,Casual'},
    {   'brand': 'Belgravia Tailors',
        'category': 'Shirts',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Light Blue',
        'description': 'Premium long-staple Oxford fabric with a classic '
                       'button-down collar. A cornerstone of preppy style.',
        'gender': 'Men',
        'id': 5,
        'image_path': 'images/products/oxford_shirt.jpg',
        'name': 'Oxford Cotton Button-Down Shirt',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 95.0,
        'season': 'All-Season',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 65,
        'style_tags': 'Old Money,Minimalist'},
    {   'brand': 'Loom & Craft',
        'category': 'Shirts',
        'collection_name': 'Sartorial Slouch',
        'color': 'White',
        'description': 'Lightweight, breathable 100% linen shirt with a modern '
                       'band collar and relaxed silhouette.',
        'gender': 'Men',
        'id': 6,
        'image_path': 'images/products/linen_band_shirt.jpg',
        'name': 'Linen Band-Collar Shirt',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 80.0,
        'season': 'Summer',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 90,
        'style_tags': 'Minimalist,Korean Fashion'},
    {   'brand': 'Systema Tech',
        'category': 'Shirts',
        'collection_name': 'System Techwear',
        'color': 'Charcoal',
        'description': 'Durable nylon-blend overshirt featuring asymmetrical '
                       'chest pockets, water-repellent coating, and magnetic '
                       'closures.',
        'gender': 'Unisex',
        'id': 7,
        'image_path': 'images/products/utility_overshirt.jpg',
        'name': 'Asymmetrical Utility Overshirt',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 140.0,
        'season': 'Fall',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 40,
        'style_tags': 'Techwear,Streetwear'},
    {   'brand': 'K-Wave Studio',
        'category': 'Shirts',
        'collection_name': 'Sartorial Slouch',
        'color': 'Sage Green',
        'description': 'Beautiful draped linen-blend blouse with drop '
                       'shoulders and a soft collarless neckline.',
        'gender': 'Women',
        'id': 8,
        'image_path': 'images/products/draped_blouse.jpg',
        'name': 'Oversized Linen Draped Blouse',
        'overlay_left_percent': 22.0,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 56.0,
        'price': 68.0,
        'season': 'Spring',
        'size_options': 'S,M,L',
        'stock_quantity': 70,
        'style_tags': 'Korean Fashion,Minimalist'},
    {   'brand': 'Systema Tech',
        'category': 'Hoodies',
        'collection_name': 'System Techwear',
        'color': 'Black',
        'description': 'Heavy fleece zip hoodie with tech-nylon panels, '
                       'waterproof zippers, and a deep scuba hood.',
        'gender': 'Unisex',
        'id': 9,
        'image_path': 'images/products/cyberpunk_hoodie.jpg',
        'name': 'Cyberpunk Shell Zip Hoodie',
        'overlay_left_percent': 20.0,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 60.0,
        'price': 160.0,
        'season': 'Winter',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 45,
        'style_tags': 'Techwear,Streetwear'},
    {   'brand': 'AetherStreet',
        'category': 'Hoodies',
        'collection_name': 'Sartorial Slouch',
        'color': 'Olive',
        'description': 'Super-thick 450gsm French Terry hoodie with a faded '
                       'acid wash and double-lined hood. Ultra-soft inside.',
        'gender': 'Unisex',
        'id': 10,
        'image_path': 'images/products/vintage_wash_hoodie.jpg',
        'name': 'Oversized Vintage Wash Hoodie',
        'overlay_left_percent': 20.0,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 60.0,
        'price': 90.0,
        'season': 'Fall,Winter',
        'size_options': 'S,M,L,XL,XXL',
        'stock_quantity': 110,
        'style_tags': 'Streetwear,Casual'},
    {   'brand': 'Belgravia Tailors',
        'category': 'Hoodies',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Oatmeal',
        'description': 'Luxurious pure Italian cashmere knit hoodie. The '
                       'ultimate high-low luxury loungewear piece.',
        'gender': 'Men',
        'id': 11,
        'image_path': 'images/products/cashmere_hoodie.jpg',
        'name': 'Cashmere Knit Pullover Hoodie',
        'overlay_left_percent': 20.0,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 60.0,
        'price': 280.0,
        'season': 'Winter',
        'size_options': 'M,L,XL',
        'stock_quantity': 25,
        'style_tags': 'Old Money,Minimalist'},
    {   'brand': 'Belgravia Tailors',
        'category': 'Jackets',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Camel',
        'description': 'Premium tailored double-breasted overcoat crafted from '
                       'heavy Italian Merino wool.',
        'gender': 'Men',
        'id': 12,
        'image_path': 'images/products/wool_coat.jpg',
        'name': 'Merino Wool Double-Breasted Coat',
        'overlay_left_percent': 20.0,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 60.0,
        'price': 420.0,
        'season': 'Winter',
        'size_options': 'M,L,XL',
        'stock_quantity': 20,
        'style_tags': 'Old Money,Minimalist'},
    {   'brand': 'Systema Tech',
        'category': 'Jackets',
        'collection_name': 'System Techwear',
        'color': 'Matte Black',
        'description': '3-layer Gore-Tex active shell with fully taped seams, '
                       'underarm vents, and modular attachments.',
        'gender': 'Unisex',
        'id': 13,
        'image_path': 'images/products/goretex_shell.jpg',
        'name': 'Modular Gore-Tex Shell Jacket',
        'overlay_left_percent': 20.0,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 60.0,
        'price': 380.0,
        'season': 'Fall,Winter',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 30,
        'style_tags': 'Techwear,Minimalist'},
    {   'brand': 'AetherStreet',
        'category': 'Jackets',
        'collection_name': 'Sartorial Slouch',
        'color': 'Silver',
        'description': 'Glossy-finish boxy down puffer jacket filled with '
                       'ethically sourced 700-fill goose down.',
        'gender': 'Unisex',
        'id': 14,
        'image_path': 'images/products/oversized_puffer.jpg',
        'name': 'Oversized Puffer Jacket',
        'overlay_left_percent': 20.0,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 60.0,
        'price': 220.0,
        'season': 'Winter',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 75,
        'style_tags': 'Streetwear,Korean Fashion'},
    {   'brand': 'K-Wave Studio',
        'category': 'Jackets',
        'collection_name': 'Sartorial Slouch',
        'color': 'Cream',
        'description': 'Exquisite cropped jacket featuring a high-quality '
                       'textured boucle tweed knit fabric and pearl buttons.',
        'gender': 'Women',
        'id': 15,
        'image_path': 'images/products/boucle_jacket.jpg',
        'name': 'Boucle Tweed Short Jacket',
        'overlay_left_percent': 20.0,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 60.0,
        'price': 145.0,
        'season': 'Spring,Fall',
        'size_options': 'S,M,L',
        'stock_quantity': 50,
        'style_tags': 'Korean Fashion,Minimalist'},
    {   'brand': 'Loom & Craft',
        'category': 'Jeans',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Indigo',
        'description': '14.5oz Japanese selvedge raw denim jeans in a classic '
                       'straight-cut fit. Build custom fades over time.',
        'gender': 'Men',
        'id': 16,
        'image_path': 'images/products/selvedge_jeans.jpg',
        'name': 'Selvedge Raw Denim Jeans',
        'overlay_left_percent': 24.0,
        'overlay_top_percent': 48.0,
        'overlay_width_percent': 52.0,
        'price': 150.0,
        'season': 'All-Season',
        'size_options': '30,32,34,36',
        'stock_quantity': 40,
        'style_tags': 'Minimalist,Casual'},
    {   'brand': 'AetherStreet',
        'category': 'Jeans',
        'collection_name': 'Sartorial Slouch',
        'color': 'Light Blue',
        'description': 'Wide-leg loose-fit jeans with hand-ripped distressed '
                       'knees and a stone-washed finish.',
        'gender': 'Unisex',
        'id': 17,
        'image_path': 'images/products/loose_distressed_jeans.jpg',
        'name': 'Loose Fit Distressed Jeans',
        'overlay_left_percent': 24.0,
        'overlay_top_percent': 48.0,
        'overlay_width_percent': 52.0,
        'price': 85.0,
        'season': 'Spring,Summer',
        'size_options': '28,30,32,34',
        'stock_quantity': 95,
        'style_tags': 'Streetwear,Casual'},
    {   'brand': 'K-Wave Studio',
        'category': 'Jeans',
        'collection_name': 'Sartorial Slouch',
        'color': 'Ecru',
        'description': 'Super high-waisted wide-leg jeans with a soft, fluid '
                       'drape and deep front pleats. Highly popular in Seoul.',
        'gender': 'Women',
        'id': 18,
        'image_path': 'images/products/wide_leg_drape_jeans.jpg',
        'name': 'Wide-Leg Drape Jeans',
        'overlay_left_percent': 24.0,
        'overlay_top_percent': 48.0,
        'overlay_width_percent': 52.0,
        'price': 75.0,
        'season': 'Spring,Summer',
        'size_options': '26,28,30,32',
        'stock_quantity': 85,
        'style_tags': 'Korean Fashion,Minimalist'},
    {   'brand': 'Systema Tech',
        'category': 'Cargo Pants',
        'collection_name': 'System Techwear',
        'color': 'Olive Drab',
        'description': 'Ripstop utility cargo pants featuring 8 3D pockets, '
                       'modular straps, and adjustable ankle toggles.',
        'gender': 'Unisex',
        'id': 19,
        'image_path': 'images/products/tactical_cargos.jpg',
        'name': 'Multi-Pocket Tactical Cargos',
        'overlay_left_percent': 24.0,
        'overlay_top_percent': 48.0,
        'overlay_width_percent': 52.0,
        'price': 170.0,
        'season': 'All-Season',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 55,
        'style_tags': 'Techwear,Streetwear'},
    {   'brand': 'K-Wave Studio',
        'category': 'Cargo Pants',
        'collection_name': 'Sartorial Slouch',
        'color': 'Beige',
        'description': 'Soft brushed cotton cargo pants with a relaxed '
                       'silhouette and clean hidden flap side pockets.',
        'gender': 'Unisex',
        'id': 20,
        'image_path': 'images/products/relaxed_cargos.jpg',
        'name': 'Relaxed Cotton Cargo Pants',
        'overlay_left_percent': 24.0,
        'overlay_top_percent': 48.0,
        'overlay_width_percent': 52.0,
        'price': 78.0,
        'season': 'Spring,Fall',
        'size_options': '28,30,32,34',
        'stock_quantity': 110,
        'style_tags': 'Korean Fashion,Casual'},
    {   'brand': 'Loom & Craft',
        'category': 'Chinos',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Navy',
        'description': 'Perfect slim-fit chinos crafted from stretch Pima '
                       'cotton twill. Extremely comfortable and versatile.',
        'gender': 'Men',
        'id': 21,
        'image_path': 'images/products/pima_chinos.jpg',
        'name': 'Pima Cotton Slim Chinos',
        'overlay_left_percent': 24.0,
        'overlay_top_percent': 48.0,
        'overlay_width_percent': 52.0,
        'price': 88.0,
        'season': 'All-Season',
        'size_options': '30,32,34,36',
        'stock_quantity': 120,
        'style_tags': 'Minimalist,Casual'},
    {   'brand': 'Belgravia Tailors',
        'category': 'Chinos',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Charcoal',
        'description': 'Tailored trousers featuring double front pleats, '
                       'adjustable side tabs, and a high-rise fit. Perfect for '
                       'an elegant Ivy league look.',
        'gender': 'Men',
        'id': 22,
        'image_path': 'images/products/pleated_trousers.jpg',
        'name': 'Pleated Tailored Trousers',
        'overlay_left_percent': 24.0,
        'overlay_top_percent': 48.0,
        'overlay_width_percent': 52.0,
        'price': 140.0,
        'season': 'Fall,Winter',
        'size_options': '30,32,34,36',
        'stock_quantity': 60,
        'style_tags': 'Old Money,Minimalist'},
    {   'brand': 'Belgravia Tailors',
        'category': 'Shoes',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Tan',
        'description': 'Handcrafted Italian calfskin leather Chelsea boots '
                       'with durable elastic side panels and a slim crepe '
                       'sole.',
        'gender': 'Men',
        'id': 23,
        'image_path': 'images/products/chelsea_boots.jpg',
        'name': 'Leather Chelsea Boots',
        'overlay_left_percent': 26.0,
        'overlay_top_percent': 86.0,
        'overlay_width_percent': 48.0,
        'price': 240.0,
        'season': 'Fall,Winter',
        'size_options': '8,9,10,11,12',
        'stock_quantity': 30,
        'style_tags': 'Old Money,Minimalist'},
    {   'brand': 'Loom & Craft',
        'category': 'Shoes',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'White',
        'description': 'Clean-profile white sneakers crafted from full-grain '
                       'Nappa leather with a margom rubber sole.',
        'gender': 'Unisex',
        'id': 24,
        'image_path': 'images/products/minimalist_white_sneakers.jpg',
        'name': 'Minimalist White Leather Sneaker',
        'overlay_left_percent': 26.0,
        'overlay_top_percent': 86.0,
        'overlay_width_percent': 48.0,
        'price': 180.0,
        'season': 'All-Season',
        'size_options': '7,8,9,10,11,12',
        'stock_quantity': 55,
        'style_tags': 'Minimalist,Casual'},
    {   'brand': 'AetherStreet',
        'category': 'Shoes',
        'collection_name': 'Sartorial Slouch',
        'color': 'Grey/White',
        'description': 'Multi-paneled chunky retro running sneakers with a '
                       'thick platform sole and detailed nylon mesh overlays.',
        'gender': 'Unisex',
        'id': 25,
        'image_path': 'images/products/chunky_sneakers.jpg',
        'name': 'Platform Chunky Retro Sneakers',
        'overlay_left_percent': 26.0,
        'overlay_top_percent': 86.0,
        'overlay_width_percent': 48.0,
        'price': 120.0,
        'season': 'All-Season',
        'size_options': '8,9,10,11',
        'stock_quantity': 70,
        'style_tags': 'Streetwear,Korean Fashion'},
    {   'brand': 'Systema Tech',
        'category': 'Shoes',
        'collection_name': 'System Techwear',
        'color': 'Matte Black',
        'description': 'High-top tactical combat boots featuring waterproof '
                       'synthetic upper, quick-lace system, and Vibram '
                       'outsoles.',
        'gender': 'Unisex',
        'id': 26,
        'image_path': 'images/products/techwear_boots.jpg',
        'name': 'Waterproof Techwear Combat Boots',
        'overlay_left_percent': 26.0,
        'overlay_top_percent': 86.0,
        'overlay_width_percent': 48.0,
        'price': 210.0,
        'season': 'Winter',
        'size_options': '8,9,10,11,12',
        'stock_quantity': 35,
        'style_tags': 'Techwear,Streetwear'},
    {   'brand': 'Belgravia Tailors',
        'category': 'Accessories',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Tortoiseshell',
        'description': 'Classic tortoiseshell D-frame sunglasses handcrafted '
                       'from premium cellulose acetate with polarized lenses.',
        'gender': 'Unisex',
        'id': 27,
        'image_path': 'images/products/acetate_sunglasses.jpg',
        'name': 'Polarized Acetate Sunglasses',
        'overlay_left_percent': 40.0,
        'overlay_top_percent': 5.0,
        'overlay_width_percent': 20.0,
        'price': 110.0,
        'season': 'Summer',
        'size_options': 'One-Size',
        'stock_quantity': 90,
        'style_tags': 'Old Money,Minimalist'},
    {   'brand': 'Systema Tech',
        'category': 'Accessories',
        'collection_name': 'System Techwear',
        'color': 'Black',
        'description': 'Heavy-duty nylon webbing belt featuring a '
                       'quick-release metal cobra buckle. Standard techwear '
                       'accessory.',
        'gender': 'Unisex',
        'id': 28,
        'image_path': 'images/products/cobra_belt.jpg',
        'name': 'Tactical Cobra Buckle Belt',
        'overlay_left_percent': 40.0,
        'overlay_top_percent': 5.0,
        'overlay_width_percent': 20.0,
        'price': 45.0,
        'season': 'All-Season',
        'size_options': 'One-Size',
        'stock_quantity': 150,
        'style_tags': 'Techwear,Streetwear'},
    {   'brand': 'Loom & Craft',
        'category': 'Accessories',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Navy',
        'description': 'Ultra-slim card wallet made from scratch-resistant '
                       'Saffiano leather. 4 card slots and center pocket.',
        'gender': 'Unisex',
        'id': 29,
        'image_path': 'images/products/saffiano_cardholder.jpg',
        'name': 'Minimalist Saffiano Leather Cardholder',
        'overlay_left_percent': 40.0,
        'overlay_top_percent': 5.0,
        'overlay_width_percent': 20.0,
        'price': 60.0,
        'season': 'All-Season',
        'size_options': 'One-Size',
        'stock_quantity': 110,
        'style_tags': 'Minimalist,Old Money'},
    {   'brand': 'Systema Tech',
        'category': 'Accessories',
        'collection_name': 'System Techwear',
        'color': 'Olive Green',
        'description': 'Waterproof military-grade nylon crossbody bag with '
                       'daisy-chain webbing, heavy carabiners, and dual '
                       'storage compartments.',
        'gender': 'Unisex',
        'id': 30,
        'image_path': 'images/products/utility_messenger_bag.jpg',
        'name': 'Nylon Messenger Utility Bag',
        'overlay_left_percent': 40.0,
        'overlay_top_percent': 5.0,
        'overlay_width_percent': 20.0,
        'price': 75.0,
        'season': 'All-Season',
        'size_options': 'One-Size',
        'stock_quantity': 85,
        'style_tags': 'Techwear,Streetwear'},
    {   'brand': 'K-Wave Studio',
        'category': 'Accessories',
        'collection_name': 'Sartorial Slouch',
        'color': 'Cream',
        'description': 'Thick ribbed fisherman beanie crafted from a soft '
                       'extrafine wool blend. A cozy Korean aesthetic '
                       'accessory.',
        'gender': 'Unisex',
        'id': 31,
        'image_path': 'images/products/ribbed_beanie.jpg',
        'name': 'Ribbed Knit Wool Beanie',
        'overlay_left_percent': 40.0,
        'overlay_top_percent': 5.0,
        'overlay_width_percent': 20.0,
        'price': 28.0,
        'season': 'Winter',
        'size_options': 'One-Size',
        'stock_quantity': 200,
        'style_tags': 'Korean Fashion,Casual'},
    {   'brand': 'Ralph Lauren Vintage',
        'category': 'Tops',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Burgundy',
        'description': 'Luxurious burgundy shawl-collar wool-blend sweater '
                       'displaying an intricate woven landscape panel of ducks '
                       'flying over a lake with a retriever. Styled over a '
                       'blue pinstriped shirt.',
        'gender': 'Men',
        'id': 2001,
        'image_path': None,
        'name': 'Tapestry Hunter Shawl Knit',
        'overlay_left_percent': 17.5,
        'overlay_top_percent': 21.5,
        'overlay_width_percent': 65.0,
        'price': 580.0,
        'season': 'Fall,Winter',
        'size_options': 'M,L,XL',
        'stock_quantity': 12,
        'style_tags': 'Old Money,Quiet Luxury,Tapestry'},
    {   'brand': 'Diznew',
        'category': 'Tops',
        'collection_name': 'System Techwear',
        'color': 'Charcoal',
        'description': 'Washed charcoal-gray heavy cotton fleece hoodie '
                       'featuring organic cut-out paneling detailed with raw, '
                       'blood-red stitched piping outlines. Streetwear aesthetic.',
        'gender': 'Unisex',
        'id': 2002,
        'image_path': None,
        'name': 'Seamed Eyelet Heavy Hoodie',
        'overlay_left_percent': 13.0,
        'overlay_top_percent': 19.0,
        'overlay_width_percent': 74.0,
        'price': 320.0,
        'season': 'Fall,Winter',
        'size_options': 'M,L,XL,XXL',
        'stock_quantity': 25,
        'style_tags': 'Streetwear,Techwear,Deconstructed'},
    {   'brand': 'System Tech',
        'category': 'Tops',
        'collection_name': 'System Techwear',
        'color': 'Navy',
        'description': 'Multi-paneled mock-neck rib-knit sweater in navy, '
                       'rust, and burnt orange, centered with an intricate '
                       'cream starburst knit graphic. Chunky textured feel.',
        'gender': 'Unisex',
        'id': 2003,
        'image_path': None,
        'name': 'Sunburst Ribbed Jumper',
        'overlay_left_percent': 14.5,
        'overlay_top_percent': 20.0,
        'overlay_width_percent': 71.0,
        'price': 280.0,
        'season': 'Fall,Winter',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 30,
        'style_tags': 'Techwear,Streetwear,Knit'},
    {   'brand': 'Sartorial Slouch',
        'category': 'Bottoms',
        'collection_name': 'Sartorial Slouch',
        'color': 'Olive',
        'description': 'Heavyweight wide-legged dark olive corduroy trousers '
                       'featuring vertical patterned jacquard tapestry panels '
                       'inset along the outer side seams.',
        'gender': 'Unisex',
        'id': 2004,
        'image_path': None,
        'name': 'Paneled Corduroy Wide Trousers',
        'overlay_left_percent': 21.0,
        'overlay_top_percent': 51.0,
        'overlay_width_percent': 58.0,
        'price': 240.0,
        'season': 'Fall,Winter',
        'size_options': '30,32,34,36',
        'stock_quantity': 18,
        'style_tags': 'Sartorial,Tapestry,Corduroy'},
    {   'brand': 'Sartorial Slouch',
        'category': 'Outerwear',
        'collection_name': 'Sartorial Slouch',
        'color': 'Slate Blue',
        'description': 'Faded slate-blue cotton canvas zip jacket with custom '
                       'embroidered travel patches down the sleeve, opening to '
                       'reveal a quilted cream and red cherry-blossom floral lining.',
        'gender': 'Unisex',
        'id': 2005,
        'image_path': None,
        'name': 'Patched Heritage Bomber',
        'overlay_left_percent': 11.5,
        'overlay_top_percent': 18.0,
        'overlay_width_percent': 77.0,
        'price': 490.0,
        'season': 'Spring,Fall',
        'size_options': 'M,L,XL',
        'stock_quantity': 10,
        'style_tags': 'Sartorial,Heritage,Embroidered'},
    {   'brand': 'Quiet Luxury Essentials',
        'category': 'Tops',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Cream',
        'description': 'Traditional heavyweight cream linen popover tunic '
                       'shirt detailed with highly intricate crimson geometric '
                       'embroidery along the split collar, front placket, and sleeves.',
        'gender': 'Unisex',
        'id': 2006,
        'image_path': None,
        'name': 'Heritage Embroidered Tunic',
        'overlay_left_percent': 16.5,
        'overlay_top_percent': 21.0,
        'overlay_width_percent': 67.0,
        'price': 350.0,
        'season': 'Spring,Summer',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 20,
        'style_tags': 'Old Money,Embroidered,Linen'},
    {   'brand': 'Sartorial Slouch',
        'category': 'Tops',
        'collection_name': 'Sartorial Slouch',
        'color': 'Grey',
        'description': 'Faded slate-gray knit crewneck wrapped with an '
                       'abstract, organic black jacquard lettering pattern '
                       'across the chest, back, and sleeves.',
        'gender': 'Unisex',
        'id': 2007,
        'image_path': None,
        'name': 'Jacquard Abstract Lettering Jumper',
        'overlay_left_percent': 15.0,
        'overlay_top_percent': 20.5,
        'overlay_width_percent': 70.0,
        'price': 210.0,
        'season': 'Fall,Winter',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 35,
        'style_tags': 'Sartorial,Streetwear,Jacquard'},
    {   'brand': 'Pikol',
        'category': 'Outerwear',
        'collection_name': 'Quiet Luxury Essentials',
        'color': 'Navy',
        'description': 'Premium dark navy blue fine-wale corduroy zip jacket '
                       'detailed with beautiful cream tapestry chest inserts '
                       'displaying soft pink and green embroidered floral patterns.',
        'gender': 'Men',
        'id': 2008,
        'image_path': None,
        'name': 'Floral Tapestry Corduroy Jacket',
        'overlay_left_percent': 12.0,
        'overlay_top_percent': 18.5,
        'overlay_width_percent': 76.0,
        'price': 460.0,
        'season': 'Fall,Winter',
        'size_options': 'M,L,XL',
        'stock_quantity': 8,
        'style_tags': 'Quiet Luxury,Tapestry,Corduroy,Floral'},
    {   'brand': 'System Tech',
        'category': 'Tops',
        'collection_name': 'System Techwear',
        'color': 'Cream',
        'description': 'Heavy cream-white cotton sweatshirt transitioning '
                       'asymmetrically into a highly textured, pixelated woven '
                       'tapestry featuring retro fighting-game combat characters.',
        'gender': 'Unisex',
        'id': 2009,
        'image_path': None,
        'name': 'Pixel Tapestry Combat Sweatshirt',
        'overlay_left_percent': 14.0,
        'overlay_top_percent': 19.5,
        'overlay_width_percent': 72.0,
        'price': 290.0,
        'season': 'Fall,Winter',
        'size_options': 'S,M,L,XL',
        'stock_quantity': 22,
        'style_tags': 'Techwear,Tapestry,Streetwear'}]
