SEED_PRODUCTS = [
    # --- Category: T-Shirts ---
    {
        "id": 1,
        "name": "Classic Heavyweight Cotton Tee",
        "description": "Boxy-fit, heavy 240gsm cotton t-shirt with a vintage wash. Prefect streetwear staple.",
        "brand": "AetherStreet",
        "category": "T-Shirts",
        "style_tags": "Streetwear,Casual",
        "color": "Black",
        "size_options": "S,M,L,XL",
        "price": 35.0,
        "gender": "Unisex",
        "season": "Summer",
        "stock_quantity": 120,
        "image_path": "images/products/classic_heavyweight_tee.jpg"
    },
    {
        "id": 2,
        "name": "Pima Cotton Minimalist Tee",
        "description": "Ultra-soft luxury Pima cotton t-shirt with a slim silhouette and clean stitched hems.",
        "brand": "Loom & Craft",
        "category": "T-Shirts",
        "style_tags": "Minimalist,Casual",
        "color": "White",
        "size_options": "S,M,L,XL",
        "price": 45.0,
        "gender": "Men",
        "season": "All-Season",
        "stock_quantity": 80,
        "image_path": "images/products/pima_minimalist_tee.jpg"
    },
    {
        "id": 3,
        "name": "Oversized Drop-Shoulder Tee",
        "description": "Wide, boxy fit tee with relaxed drop shoulders and an embroidered chest logo. Inspired by Seoul streetwear.",
        "brand": "K-Wave Studio",
        "category": "T-Shirts",
        "style_tags": "Korean Fashion,Streetwear",
        "color": "Beige",
        "size_options": "M,L,XL",
        "price": 38.0,
        "gender": "Unisex",
        "season": "Summer",
        "stock_quantity": 150,
        "image_path": "images/products/oversized_drop_tee.jpg"
    },
    {
        "id": 4,
        "name": "Pique Cotton Polo Shirt",
        "description": "Breathable pique knit polo with mother-of-pearl buttons and subtle crown embroidery. Timeless class.",
        "brand": "Belgravia Tailors",
        "category": "T-Shirts",
        "style_tags": "Old Money,Casual",
        "color": "Navy",
        "size_options": "S,M,L,XL,XXL",
        "price": 75.0,
        "gender": "Men",
        "season": "Summer",
        "stock_quantity": 50,
        "image_path": "images/products/pique_polo.jpg"
    },

    # --- Category: Shirts ---
    {
        "id": 5,
        "name": "Oxford Cotton Button-Down Shirt",
        "description": "Premium long-staple Oxford fabric with a classic button-down collar. A cornerstone of preppy style.",
        "brand": "Belgravia Tailors",
        "category": "Shirts",
        "style_tags": "Old Money,Minimalist",
        "color": "Light Blue",
        "size_options": "S,M,L,XL",
        "price": 95.0,
        "gender": "Men",
        "season": "All-Season",
        "stock_quantity": 65,
        "image_path": "images/products/oxford_shirt.jpg"
    },
    {
        "id": 6,
        "name": "Linen Band-Collar Shirt",
        "description": "Lightweight, breathable 100% linen shirt with a modern band collar and relaxed silhouette.",
        "brand": "Loom & Craft",
        "category": "Shirts",
        "style_tags": "Minimalist,Korean Fashion",
        "color": "White",
        "size_options": "S,M,L,XL",
        "price": 80.0,
        "gender": "Men",
        "season": "Summer",
        "stock_quantity": 90,
        "image_path": "images/products/linen_band_shirt.jpg"
    },
    {
        "id": 7,
        "name": "Asymmetrical Utility Overshirt",
        "description": "Durable nylon-blend overshirt featuring asymmetrical chest pockets, water-repellent coating, and magnetic closures.",
        "brand": "Systema Tech",
        "category": "Shirts",
        "style_tags": "Techwear,Streetwear",
        "color": "Charcoal",
        "size_options": "S,M,L,XL",
        "price": 140.0,
        "gender": "Unisex",
        "season": "Fall",
        "stock_quantity": 40,
        "image_path": "images/products/utility_overshirt.jpg"
    },
    {
        "id": 8,
        "name": "Oversized Linen Draped Blouse",
        "description": "Beautiful draped linen-blend blouse with drop shoulders and a soft collarless neckline.",
        "brand": "K-Wave Studio",
        "category": "Shirts",
        "style_tags": "Korean Fashion,Minimalist",
        "color": "Sage Green",
        "size_options": "S,M,L",
        "price": 68.0,
        "gender": "Women",
        "season": "Spring",
        "stock_quantity": 70,
        "image_path": "images/products/draped_blouse.jpg"
    },

    # --- Category: Hoodies ---
    {
        "id": 9,
        "name": "Cyberpunk Shell Zip Hoodie",
        "description": "Heavy fleece zip hoodie with tech-nylon panels, waterproof zippers, and a deep scuba hood.",
        "brand": "Systema Tech",
        "category": "Hoodies",
        "style_tags": "Techwear,Streetwear",
        "color": "Black",
        "size_options": "S,M,L,XL",
        "price": 160.0,
        "gender": "Unisex",
        "season": "Winter",
        "stock_quantity": 45,
        "image_path": "images/products/cyberpunk_hoodie.jpg"
    },
    {
        "id": 10,
        "name": "Oversized Vintage Wash Hoodie",
        "description": "Super-thick 450gsm French Terry hoodie with a faded acid wash and double-lined hood. Ultra-soft inside.",
        "brand": "AetherStreet",
        "category": "Hoodies",
        "style_tags": "Streetwear,Casual",
        "color": "Olive",
        "size_options": "S,M,L,XL,XXL",
        "price": 90.0,
        "gender": "Unisex",
        "season": "Fall,Winter",
        "stock_quantity": 110,
        "image_path": "images/products/vintage_wash_hoodie.jpg"
    },
    {
        "id": 11,
        "name": "Cashmere Knit Pullover Hoodie",
        "description": "Luxurious pure Italian cashmere knit hoodie. The ultimate high-low luxury loungewear piece.",
        "brand": "Belgravia Tailors",
        "category": "Hoodies",
        "style_tags": "Old Money,Minimalist",
        "color": "Oatmeal",
        "size_options": "M,L,XL",
        "price": 280.0,
        "gender": "Men",
        "season": "Winter",
        "stock_quantity": 25,
        "image_path": "images/products/cashmere_hoodie.jpg"
    },

    # --- Category: Jackets ---
    {
        "id": 12,
        "name": "Merino Wool Double-Breasted Coat",
        "description": "Premium tailored double-breasted overcoat crafted from heavy Italian Merino wool.",
        "brand": "Belgravia Tailors",
        "category": "Jackets",
        "style_tags": "Old Money,Minimalist",
        "color": "Camel",
        "size_options": "M,L,XL",
        "price": 420.0,
        "gender": "Men",
        "season": "Winter",
        "stock_quantity": 20,
        "image_path": "images/products/wool_coat.jpg"
    },
    {
        "id": 13,
        "name": "Modular Gore-Tex Shell Jacket",
        "description": "3-layer Gore-Tex active shell with fully taped seams, underarm vents, and modular attachments.",
        "brand": "Systema Tech",
        "category": "Jackets",
        "style_tags": "Techwear,Minimalist",
        "color": "Matte Black",
        "size_options": "S,M,L,XL",
        "price": 380.0,
        "gender": "Unisex",
        "season": "Fall,Winter",
        "stock_quantity": 30,
        "image_path": "images/products/goretex_shell.jpg"
    },
    {
        "id": 14,
        "name": "Oversized Puffer Jacket",
        "description": "Glossy-finish boxy down puffer jacket filled with ethically sourced 700-fill goose down.",
        "brand": "AetherStreet",
        "category": "Jackets",
        "style_tags": "Streetwear,Korean Fashion",
        "color": "Silver",
        "size_options": "S,M,L,XL",
        "price": 220.0,
        "gender": "Unisex",
        "season": "Winter",
        "stock_quantity": 75,
        "image_path": "images/products/oversized_puffer.jpg"
    },
    {
        "id": 15,
        "name": "Boucle Tweed Short Jacket",
        "description": "Exquisite cropped jacket featuring a high-quality textured boucle tweed knit fabric and pearl buttons.",
        "brand": "K-Wave Studio",
        "category": "Jackets",
        "style_tags": "Korean Fashion,Minimalist",
        "color": "Cream",
        "size_options": "S,M,L",
        "price": 145.0,
        "gender": "Women",
        "season": "Spring,Fall",
        "stock_quantity": 50,
        "image_path": "images/products/boucle_jacket.jpg"
    },

    # --- Category: Jeans ---
    {
        "id": 16,
        "name": "Selvedge Raw Denim Jeans",
        "description": "14.5oz Japanese selvedge raw denim jeans in a classic straight-cut fit. Build custom fades over time.",
        "brand": "Loom & Craft",
        "category": "Jeans",
        "style_tags": "Minimalist,Casual",
        "color": "Indigo",
        "size_options": "30,32,34,36",
        "price": 150.0,
        "gender": "Men",
        "season": "All-Season",
        "stock_quantity": 40,
        "image_path": "images/products/selvedge_jeans.jpg"
    },
    {
        "id": 17,
        "name": "Loose Fit Distressed Jeans",
        "description": "Wide-leg loose-fit jeans with hand-ripped distressed knees and a stone-washed finish.",
        "brand": "AetherStreet",
        "category": "Jeans",
        "style_tags": "Streetwear,Casual",
        "color": "Light Blue",
        "size_options": "28,30,32,34",
        "price": 85.0,
        "gender": "Unisex",
        "season": "Spring,Summer",
        "stock_quantity": 95,
        "image_path": "images/products/loose_distressed_jeans.jpg"
    },
    {
        "id": 18,
        "name": "Wide-Leg Drape Jeans",
        "description": "Super high-waisted wide-leg jeans with a soft, fluid drape and deep front pleats. Highly popular in Seoul.",
        "brand": "K-Wave Studio",
        "category": "Jeans",
        "style_tags": "Korean Fashion,Minimalist",
        "color": "Ecru",
        "size_options": "26,28,30,32",
        "price": 75.0,
        "gender": "Women",
        "season": "Spring,Summer",
        "stock_quantity": 85,
        "image_path": "images/products/wide_leg_drape_jeans.jpg"
    },

    # --- Category: Cargo Pants ---
    {
        "id": 19,
        "name": "Multi-Pocket Tactical Cargos",
        "description": "Ripstop utility cargo pants featuring 8 3D pockets, modular straps, and adjustable ankle toggles.",
        "brand": "Systema Tech",
        "category": "Cargo Pants",
        "style_tags": "Techwear,Streetwear",
        "color": "Olive Drab",
        "size_options": "S,M,L,XL",
        "price": 170.0,
        "gender": "Unisex",
        "season": "All-Season",
        "stock_quantity": 55,
        "image_path": "images/products/tactical_cargos.jpg"
    },
    {
        "id": 20,
        "name": "Relaxed Cotton Cargo Pants",
        "description": "Soft brushed cotton cargo pants with a relaxed silhouette and clean hidden flap side pockets.",
        "brand": "K-Wave Studio",
        "category": "Cargo Pants",
        "style_tags": "Korean Fashion,Casual",
        "color": "Beige",
        "size_options": "28,30,32,34",
        "price": 78.0,
        "gender": "Unisex",
        "season": "Spring,Fall",
        "stock_quantity": 110,
        "image_path": "images/products/relaxed_cargos.jpg"
    },

    # --- Category: Chinos ---
    {
        "id": 21,
        "name": "Pima Cotton Slim Chinos",
        "description": "Perfect slim-fit chinos crafted from stretch Pima cotton twill. Extremely comfortable and versatile.",
        "brand": "Loom & Craft",
        "category": "Chinos",
        "style_tags": "Minimalist,Casual",
        "color": "Navy",
        "size_options": "30,32,34,36",
        "price": 88.0,
        "gender": "Men",
        "season": "All-Season",
        "stock_quantity": 120,
        "image_path": "images/products/pima_chinos.jpg"
    },
    {
        "id": 22,
        "name": "Pleated Tailored Trousers",
        "description": "Tailored trousers featuring double front pleats, adjustable side tabs, and a high-rise fit. Perfect for an elegant Ivy league look.",
        "brand": "Belgravia Tailors",
        "category": "Chinos",
        "style_tags": "Old Money,Minimalist",
        "color": "Charcoal",
        "size_options": "30,32,34,36",
        "price": 140.0,
        "gender": "Men",
        "season": "Fall,Winter",
        "stock_quantity": 60,
        "image_path": "images/products/pleated_trousers.jpg"
    },

    # --- Category: Shoes ---
    {
        "id": 23,
        "name": "Leather Chelsea Boots",
        "description": "Handcrafted Italian calfskin leather Chelsea boots with durable elastic side panels and a slim crepe sole.",
        "brand": "Belgravia Tailors",
        "category": "Shoes",
        "style_tags": "Old Money,Minimalist",
        "color": "Tan",
        "size_options": "8,9,10,11,12",
        "price": 240.0,
        "gender": "Men",
        "season": "Fall,Winter",
        "stock_quantity": 30,
        "image_path": "images/products/chelsea_boots.jpg"
    },
    {
        "id": 24,
        "name": "Minimalist White Leather Sneaker",
        "description": "Clean-profile white sneakers crafted from full-grain Nappa leather with a margom rubber sole.",
        "brand": "Loom & Craft",
        "category": "Shoes",
        "style_tags": "Minimalist,Casual",
        "color": "White",
        "size_options": "7,8,9,10,11,12",
        "price": 180.0,
        "gender": "Unisex",
        "season": "All-Season",
        "stock_quantity": 55,
        "image_path": "images/products/minimalist_white_sneakers.jpg"
    },
    {
        "id": 25,
        "name": "Platform Chunky Retro Sneakers",
        "description": "Multi-paneled chunky retro running sneakers with a thick platform sole and detailed nylon mesh overlays.",
        "brand": "AetherStreet",
        "category": "Shoes",
        "style_tags": "Streetwear,Korean Fashion",
        "color": "Grey/White",
        "size_options": "8,9,10,11",
        "price": 120.0,
        "gender": "Unisex",
        "season": "All-Season",
        "stock_quantity": 70,
        "image_path": "images/products/chunky_sneakers.jpg"
    },
    {
        "id": 26,
        "name": "Waterproof Techwear Combat Boots",
        "description": "High-top tactical combat boots featuring waterproof synthetic upper, quick-lace system, and Vibram outsoles.",
        "brand": "Systema Tech",
        "category": "Shoes",
        "style_tags": "Techwear,Streetwear",
        "color": "Matte Black",
        "size_options": "8,9,10,11,12",
        "price": 210.0,
        "gender": "Unisex",
        "season": "Winter",
        "stock_quantity": 35,
        "image_path": "images/products/techwear_boots.jpg"
    },

    # --- Category: Accessories ---
    {
        "id": 27,
        "name": "Polarized Acetate Sunglasses",
        "description": "Classic tortoiseshell D-frame sunglasses handcrafted from premium cellulose acetate with polarized lenses.",
        "brand": "Belgravia Tailors",
        "category": "Accessories",
        "style_tags": "Old Money,Minimalist",
        "color": "Tortoiseshell",
        "size_options": "One-Size",
        "price": 110.0,
        "gender": "Unisex",
        "season": "Summer",
        "stock_quantity": 90,
        "image_path": "images/products/acetate_sunglasses.jpg"
    },
    {
        "id": 28,
        "name": "Tactical Cobra Buckle Belt",
        "description": "Heavy-duty nylon webbing belt featuring a quick-release metal cobra buckle. Standard techwear accessory.",
        "brand": "Systema Tech",
        "category": "Accessories",
        "style_tags": "Techwear,Streetwear",
        "color": "Black",
        "size_options": "One-Size",
        "price": 45.0,
        "gender": "Unisex",
        "season": "All-Season",
        "stock_quantity": 150,
        "image_path": "images/products/cobra_belt.jpg"
    },
    {
        "id": 29,
        "name": "Minimalist Saffiano Leather Cardholder",
        "description": "Ultra-slim card wallet made from scratch-resistant Saffiano leather. 4 card slots and center pocket.",
        "brand": "Loom & Craft",
        "category": "Accessories",
        "style_tags": "Minimalist,Old Money",
        "color": "Navy",
        "size_options": "One-Size",
        "price": 60.0,
        "gender": "Unisex",
        "season": "All-Season",
        "stock_quantity": 110,
        "image_path": "images/products/saffiano_cardholder.jpg"
    },
    {
        "id": 30,
        "name": "Nylon Messenger Utility Bag",
        "description": "Waterproof military-grade nylon crossbody bag with daisy-chain webbing, heavy carabiners, and dual storage compartments.",
        "brand": "Systema Tech",
        "category": "Accessories",
        "style_tags": "Techwear,Streetwear",
        "color": "Olive Green",
        "size_options": "One-Size",
        "price": 75.0,
        "gender": "Unisex",
        "season": "All-Season",
        "stock_quantity": 85,
        "image_path": "images/products/utility_messenger_bag.jpg"
    },
    {
        "id": 31,
        "name": "Ribbed Knit Wool Beanie",
        "description": "Thick ribbed fisherman beanie crafted from a soft extrafine wool blend. A cozy Korean aesthetic accessory.",
        "brand": "K-Wave Studio",
        "category": "Accessories",
        "style_tags": "Korean Fashion,Casual",
        "color": "Cream",
        "size_options": "One-Size",
        "price": 28.0,
        "gender": "Unisex",
        "season": "Winter",
        "stock_quantity": 200,
        "image_path": "images/products/ribbed_beanie.jpg"
    }
]
